name: Unit Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs the test on backend
        run: docker-compose -f docker-compose-test.yaml up --build --abort-on-container-exit
